### ISSUE TITLE
Ansible task: Ensure that sudo is installed

### ISSUE THREAD

**Issue by drew9781** [chriswayg/packer-proxmox-templates#4]
Hello, I'm running into an issue with the playbook on debian 10.
I'm troubleshooting it, but I was wondering if you had any insight :)

```   
proxmox: TASK [ansible-initial-server : Ensure that sudo is installed.] *****************
    proxmox: Saturday 02 May 2020  10:27:36 -0400 (0:00:02.980)       0:00:04.832 **********
    proxmox: fatal: [default]: FAILED! => changed=false
    proxmox:   cmd: pkg_info -Iq inst:sudo
    proxmox:   msg: '[Errno 2] No such file or directory'
    proxmox:   rc: 2
    proxmox:    to retry, use: --limit @/home/aenglema/packer-proxmox-templates-1.5/debian-10-amd64-proxmox/playbook/server-template.retry
    proxmox:
    proxmox: PLAY RECAP *********************************************************************
    proxmox: default                    : ok=2    changed=0    unreachable=0    failed=1
```
